dbtlearn:
  outputs:
    dev:
      dbname: mydatabase
      host: postgres
      pass: mypassword
      port: 5432
      schema: dbt
      threads: 1
      type: postgres
      user: myuser
  target: dev
