version: 2

models:
  - name: fct_orders
    description: "Fact table containing one row per order, with total_amount calculated"
    columns:
      - name: order_id
        description: "Unique identifier for the order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Foreign key to dim_customers"
        tests:
          - not_null
      - name: total_amount
        description: "Sum of total_price from order_items, per order"
        tests:
          - not_null
